### ISSUE TITLE
Finalshell has been updated, the latest version cannot use FinalShell-keygen, please update

### ISSUE THREAD

**Issue by 759852125** [Kris2002047/FinalShell-keygen#2]
Finalshell has been updated, the latest version cannot use FinalShell-keygen, please update

**Comment by Kris2002047** [comment]
Hello.
I'm sorry, but you're right.
It seems that there is something wrong on FinalShell v3.9.6.2.
Please install FinalShell **v3.9.5.7** or earlier instead.
And we'll rush to update our project.
Thank you.
